let ques = [
  {
    numb: 1,
    question: "What does HTML stand for?",
    answer: "Hyper Text Markup Language",
    options: [
      "Hyper Tool Markup Language",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 2,
    question: "what does CSS stand for?",
    answer: "Cascading Style Sheet",
    options: [
      "Cascading Sheet Scripts",
      "Cascading Sheet Script",
      "Coding Sheet Scripts",
      "Cascading Sheet Server",
    ],
  },
  {
    numb: 3,
    question: "what does PHP stand for?",
    answer: "Hypertext Preprocessor",
    options: [
      "Hypertext Programming",
      "Hypertext Preprogramming",
      "Hometext Preprocessor",
      "Hypertext Preprocessor",
    ],
  },
  {
    numb: 4,
    question: "what does SQL stand for?",
    answer: "Structure Query Language",
    options: [
      "Style Query Language",
      "Structure Question Language",
      "Structure Query Language",
      "Statement Query Language",
    ],
  },
  {
    numb: 5,
    question: "what does XML stand for?",
    answer: "Extensible Markup Language",
    options: [
      "Executable Markup Language",
      "Extensible Markup Language",
      "Extensible Mark Language",
      "Expensive Markup Language",
    ],
  },
  {
    numb: 6,
    question: "What Javascript?",
    answer: "A programming Language",
    options: [
      "Hyper Tool Markup Language5",
      "A programming Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 7,
    question: "What is Java?",
    answer: "A programming Language",
    options: [
      "A programming Language",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 8,
    question: "What is Nigeria?",
    answer: "A country",
    options: [
      "Hyper Tool Markup Language7",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 9,
    question: "What is Mango?",
    answer: "A fruit",
    options: [
      "Fruit",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 10,
    question: "What Orange?",
    answer: "A fruit",
    options: [
      "A fruit",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 11,
    question: "What is pawpaw?",
    answer: "A fruit",
    options: [
      "Hyper Tool Markup1 Language",
      "Hyper Text Markup Language",
      "A fruit",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 12,
    question: "What is Apple?",
    answer: "A fruit",
    options: [
      "Hyper Tool Markup2 Language",
      "A fruit",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 13,
    question: "What is Banana?",
    answer: "A fruit",
    options: [
      "Hyper Tool Markup3 Language",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "A fruit",
    ],
  },
  {
    numb: 14,
    question: "Example of a Car",
    answer: "Benz",
    options: [
      "Benz",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 15,
    question: "Example of a Car",
    answer: "Toyota",
    options: [
      "Hyper Tool Markup5 Language",
      "Toyata",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 16,
    question: "Example of a Car",
    answer: "Honda",
    options: [
      "Hyper Tool Markup6 Language",
      "Honda",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 17,
    question: "Example of a Car",
    answer: "Ford",
    options: [
      "Hyper Tool Markup7 Language",
      "Hyper Text Markup Language",
      "Ford",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 18,
    question: "Example of a Car",
    answer: "Mazda",
    options: [
      "Hyper Tool Markup8 Language",
      "Mazda",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 19,
    question: "Example of Color",
    answer: "Red",
    options: [
      "Red",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 20,
    question: "Example of Color",
    answer: "Yellow",
    options: [
      "Hyper Tool1 Markup Language",
      "Hyper Text Markup Language",
      "Yellow",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 21,
    question: "Example of Color",
    answer: "Blue",
    options: [
      "Hyper Tool2 Markup Language",
      "Blue",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 22,
    question: "Example of Color",
    answer: "Green",
    options: [
      "Hyper Tool3 Markup Language",
      "Hyper Text Markup Language",
      "Green",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 23,
    question: "Example of Color",
    answer: "Purple",
    options: [
      "Hyper Tool4 Markup Language",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Purple",
    ],
  },
  {
    numb: 24,
    question: "Example of Color",
    answer: "Black",
    options: [
      "Hyper Tool5 Markup Language",
      "Black",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 25,
    question: "Example of a Sport",
    answer: "Foot Ball",
    options: [
      "Hyper Tool6 Markup Language",
      "Foot Ball",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 26,
    question: "Example of a Sport",
    answer: "Basket Ball",
    options: [
      "Basket Ball",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 27,
    question: "Example of a Sport",
    answer: "Boxing",
    options: [
      "Hyper Tool8 Markup Language",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Boxing",
    ],
  },
  {
    numb: 28,
    question: "Example of a Sport",
    answer: "Volley Ball",
    options: [
      "Hyper Tool9 Markup Language",
      "Volley Ball",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 29,
    question: "Example of a Sport",
    answer: "Rugby",
    options: [
      "Rugby",
      "Hyper Text1 Markup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 30,
    question: "Capital of Imo State",
    answer: "Owerri",
    options: [
      "Hyper Tool Markup Language",
      "Hyper Text2 Markup Language",
      "Home Tool Markup Language",
      "Owerri",
    ],
  },
  {
    numb: 31,
    question: "Capital od Abia State",
    answer: "Umuahaia",
    options: [
      "Hyper Tool Markup Language",
      "Umuahaia",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 32,
    question: "Capital of Lagos State",
    answer: "Ikeja",
    options: [
      "Hyper Tool Markup Language",
      "Hyper Text Markup Language",
      "Ikeja",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 33,
    question: "Capital of Rivers State",
    answer: "Port harcourt",
    options: [
      "Port harcourt",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Hyperlin5ks and Text Markup Language",
    ],
  },
  {
    numb: 34,
    question: "Capital of Enugu State",
    answer: "Enugu",
    options: [
      "Hyper Tool Markup Language",
      "Hyper Text Mark6up Language",
      "Enugu",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 35,
    question: "Capital of Akwa Ibom State",
    answer: "Uyo",
    options: [
      "Hyper Tool Markup Language",
      "Uyo",
      "Home Tool Markup 7Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 36,
    question: "Capital of Bayelsa State",
    answer: "Yenegoa",
    options: [
      "Yenegoa",
      "Hyper Text Markup Language",
      "Home Tool Markup 8Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 37,
    question: "Capital of Benue State",
    answer: "Makurdi",
    options: [
      "Hyper Tool Markup Language",
      "Hyper Text Markup Language",
      "Home Tool 9Markup Language",
      "Makurdi",
    ],
  },
  {
    numb: 38,
    question: "Capital of Sokoto State",
    answer: "Sokoto",
    options: [
      "Hyper Tool Markup Language",
      "Hyper Text Markup Language",
      "Sokoto",
      "Hy1perlinks and Text Markup Language",
    ],
  },
  {
    numb: 39,
    question: "Capital of Plateu State",
    answer: "Jos",
    options: [
      "Hyper Tool Markup Language",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Jos",
    ],
  },
  {
    numb: 40,
    question: "What is the biggest river in Nigeria",
    answer: "River Niger",
    options: [
      "Hyper Tool Markup Language",
      "Hyper Text Markup Language",
      "River Niger",
      "Hy3perlinks and Text Markup Language",
    ],
  },
  {
    numb: 41,
    question: "How many colors are in Nigeria's flag",
    answer: "Two",
    options: [
      "Two",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 42,
    question: "How many states in Nigeria",
    answer: "36",
    options: [
      "Hyper Tool Markup Language",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "36",
    ],
  },
  {
    numb: 43,
    question: "What is a computer?",
    answer: "A computing device",
    options: [
      "Hyper Tool Markup Language",
      "A computing device",
      "Home Tool Markup Language",
      "H6yperlinks and Text Markup Language",
    ],
  },
  {
    numb: 44,
    question: "How many months make a year",
    answer: "12",
    options: [
      "12",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 45,
    question: "Example of an animal",
    answer: "Dog",
    options: [
      "Hyper Tool Markup Language",
      "Hyper Text Markup Language",
      "8Home Tool Markup Language",
      "Dog",
    ],
  },
  {
    numb: 46,
    question: "Example of an animal",
    answer: "Goat",
    options: [
      "Goat",
      "Hyper Text Markup Language",
      "9Home Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 47,
    question: "Example of an animal",
    answer: "Cat",
    options: [
      "Hyper Tool Markup Language",
      "Hyper Text Markup Language",
      "Cat",
      "1Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 48,
    question: "Example of an animal",
    answer: "Rat",
    options: [
      "Hyper Tool Markup Language",
      "Rat",
      "Ho2me Tool Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 49,
    question: "Example of a fish",
    answer: "Whale",
    options: [
      "Whale",
      "Hyper Text Markup Language",
      "Home To3ol Markup Language",
      "Hyperlinks and Text Markup Language",
    ],
  },
  {
    numb: 50,
    question: "Example of a fish",
    answer: "Shark",
    options: [
      "Hyper Tool Markup Language",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Shark",
    ],
  },
];
